Repository VakVakVerse/vvv, pull requests merged in 2024-04, with the labels that each got.

#9 feat(#7) : 로그인 브랜치 생성, public에 소셜 로그인 로고 추가 - google.svg, kakao.svg
  public/images/google.svg
  public/images/kakao.svg
  src/app/(nonAuth)/login/page.tsx
Labels: documentation, enhancement

#19 feat(#18) : 유저 정보 테이블 컬럼추가로 인한 타입 파일 변경
  src/types/supabase.d.ts
Labels: documentation, enhancement

#21 Feat(#14) contentEditable 옵션을 사용한 기본 에디터 컴포넌트 제작
  src/app/(auth)/editor/page.tsx
  src/app/globals.css
  src/components/editor/BasicEditor.tsx
Labels: enhancement

#30 Feat(#29): 기본 에디터에 이미지 추가 기능 신규
  src/app/(auth)/editor/page.tsx
  src/app/globals.css
  src/components/editor/BasicEditor.tsx
  src/components/editor/ImageInput.tsx
Labels: enhancement

#37 feat(#22) : 회원가입 유저 정보 DB-userInfo에 저장완료, 로그인 url 에러 버그 해결중
  package.json
  src/app/(nonAuth)/join/[...nextauth]/route.ts
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/[...nextauth]/route.ts
  src/app/(nonAuth)/login/page.tsx
  src/app/(nonAuth)/main/main.tsx
  src/app/provider.tsx
  src/components/join/AllowOpenInfo.tsx
  src/hooks/useInput.ts
  src/shared/join/joinApi.ts
  src/shared/store.ts
  src/types/types.ts
  tsconfig.json
Labels: bug, documentation, enhancement

#38 feat(#27) : 메인 - 맞춤 배너 광고 작업
  next.config.mjs
  src/app/page.tsx
  src/components/main/MainBanner.tsx
Labels: documentation, enhancement

#41 feat(#11) : 커뮤니티 글 목록 구현
  src/app/(nonAuth)/community/page.tsx
  src/components/search/Search.tsx
  src/query/community/mutation.ts
  src/util/util.ts
Labels: documentation, enhancement

#46 feat(#44) : 로그인 - app루트에 nextauthprovider.tsx생성 및 layout에 설정 , 로그인 시 store에 uid 넣을 수 있게 store세팅
  src/app/(nonAuth)/login/[...nextauth]/route.ts
  src/app/(nonAuth)/login/page.tsx
  src/app/NextAuthProvider.tsx
  src/app/layout.tsx
  src/shared/join/joinApi.ts
  src/shared/store.ts
  src/shared/supabase/supabase.ts
  src/util/util.ts
Labels: documentation, enhancement

#47 Feat(#31): 글자 폰트 바꾸기 기능 신규
  src/components/editor/BasicEditor.tsx
Labels: enhancement

#48 Feat(#5) : 핫한 게시물 영역 데이터 조회 및 슬라이드 기능 작업
  src/app/page.tsx
  src/components/main/TopLikedBoard.tsx
  src/shared/miain/api.ts
  src/types/types.ts
Labels: documentation, enhancement

#55 Feat(#51): 글자 컬러 및 배경색 변경 기능 신규
  src/components/editor/BasicEditor.tsx
  src/components/editor/ChangeFontBackground.tsx
  src/components/editor/ChangeFontColor.tsx
  src/components/editor/ChangeFontSize.tsx
  src/components/editor/ChangeFontStyle.tsx
  src/components/editor/SelectMusic.tsx
Labels: enhancement

#56 feat(#54) : 로그인 - 비밀번호 찾기 구현 및 비밀번호 찾기 모달에 영향을 주는 css, 함수, 태그 겹침 버그 해결 중
  public/images/findPassword.svg
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/layout.tsx
  src/app/(nonAuth)/login/[...nextauth]/route.ts
  src/app/(nonAuth)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/shared/login/loginApi.ts
  src/shared/store.ts
  src/types/types.ts
  src/util/Modal.tsx
Labels: bug, documentation, enhancement

#57 Feat(#26) : 메인 음악추천 컨텐츠 - 영역 퍼스널 진단 유무에 따른 추천 데이터 로직 분기 작업 / 추가 버튼 클릭 시 현재 재생목록 데이터 추가 작업
  src/app/page.tsx
  src/components/main/GenreMusicItem.tsx
  src/components/main/GenreMusicList.tsx
  src/components/main/MainBanner.tsx
  src/components/main/RandomMusicList.tsx
  src/components/main/RecommendationMusicList.tsx
  src/components/main/TopLikedBoard.tsx
  src/shared/main/api.ts
  src/shared/miain/api.ts
  src/types/types.ts
  src/util/main/util.ts
Labels: documentation, enhancement

#60 Feat(#59): 실행취소, 다시실행 버튼 신규
  src/app/globals.css
  src/components/editor/ActionButton.tsx
  src/components/editor/BasicEditor.tsx
Labels: documentation, enhancement

#65 Feat/editor
  src/app/(auth)/editor/page.tsx
  src/components/editor/BasicEditor.tsx
  src/components/editor/SelectMusic.tsx
Labels: enhancement

#68 Feat(#61,#67)/Fix(#64) : 버그 수정 및 임시 값에서 실제 값으로 변경
  src/components/main/GenreMusicItem.tsx
  src/components/main/GenreMusicList.tsx
  src/components/main/MainBanner.tsx
  src/shared/main/api.ts
  src/types/supabase.d.ts
  src/types/types.ts
Labels: bug, enhancement

#69 Feat(#66): 정렬 기능(좌측, 중앙, 우측, 양쪽) 신규
  public/images/align-center.svg
  public/images/align-full.svg
  public/images/align-left.svg
  public/images/align-right.svg
  public/images/redo.svg
  public/images/undo.svg
  src/components/editor/ActionButton.tsx
  src/components/editor/BasicEditor.tsx
Labels: enhancement

#71 Feat(#52) : 커뮤니티,노래 검색, 노래 검색 모달 구현 완료
  src/app/(nonAuth)/community/page.tsx
  src/app/(nonAuth)/search/page.tsx
  src/app/page.tsx
  src/components/player/MusicPlayer.tsx
  src/components/search/MusicSearch.tsx
  src/components/search/MusicSearchModal.tsx
  src/components/search/Search.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchedCommunityData.tsx
  src/components/search/SearchedMusicData.tsx
  src/shared/store/searchStore.ts
  src/types/supabase.ts
  src/types/types.ts
  src/util/util.ts
Labels: enhancement

#78 fix(#74) : 로그인 - store에 현재 로그인한 유저의 uid가 저장되려면 로그인 화면을 가야했던 문제 해결
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/page.tsx
  src/app/provider.tsx
  src/components/main/MainBanner.tsx
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/shared/main/api.ts
  src/types/types.ts
Labels: bug, documentation, enhancement

#79 Feat(#77) : 메인 페이지에서 사용하는 타입 분리
  src/components/main/GenreMusicItem.tsx
  src/components/main/MainBanner.tsx
  src/shared/main/api.ts
  src/types/main/types.ts
  src/types/types.ts
Labels: documentation

#81 Dir(#80,#53) : 로그인, 회원가입 type - src/types/loginJoin 폴더로 분리, 소셜로그인 기능 폴더 및 파일 생성
  src/app/(nonAuth)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/socialLogin/page.tsx
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/types/loginJoin/types.ts
  src/types/types.ts
Labels: documentation, enhancement

#87 Feat(#86) : Header, Footer 생성
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
Labels: documentation, enhancement

#88 Feat(#82) - 로그인 - 구글 로그인 완성 - DB로 보낼 uid 꺼내기 중
  src/app/(nonAuth)/login/page.tsx
  src/app/NextAuthProvider.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/socialLogin/page.tsx
  src/middleware.ts
Labels: documentation, enhancement

#92 Feat(#28,#89,#90,#91) : 마이페이지 닉네임/프로필 이미지 변경 및 마이플레이리스트 노래 삭제 기능
  src/app/(auth)/mypage/page.tsx
  src/components/mypage/CheckboxItem.tsx
  src/components/mypage/Modal.tsx
  src/components/mypage/MyInfo.tsx
  src/middleware.ts
  src/shared/mypage/api.ts
  src/types/mypage/types.ts
Labels: documentation, enhancement

#96 feat(#83) : 구글 로그인 완료 및 카카오 로그인 세팅
  src/app/(nonAuth)/join/page.tsx
  src/app/UserProvider.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/shared/join/joinApi.ts
  src/shared/login/loginApi.ts
  src/types/loginJoin/types.ts
  src/types/supabase.ts
Labels: documentation, enhancement

#98 Feat(#93) : 마이페이지 - 내 게시글 조회 및 페이지네이션 작업
  src/app/(auth)/mypage/page.tsx
  src/components/mypage/MyInfo.tsx
  src/components/mypage/Pagination.tsx
  src/components/mypage/WriteList.tsx
  src/shared/mypage/api.ts
Labels: documentation, enhancement

#105 Feat/Dir(#104) : 로그인 - 로그아웃 버튼 분리 및 라우트 설정, 커스텀 로그아웃 설정
  src/app/(auth)/signout/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/components/logout/LogOutButton.tsx
Labels: documentation, enhancement
